name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: python -m unittest tests/unit_test.py

      - name: Run Integration Tests
        run: python -m unittest tests/integration_test.py

      - name: Run End-to-End Tests
        run: python -m unittest tests/end-to-end_test.py

      - name: Run Mock Tests
        run: python -m unittest tests/mock_test.py
